CREATE DATABASE LibraryDb
GO

USE LibraryDb
GO

CREATE TABLE Genres
(
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	[Name] NVARCHAR(30) NOT NULL
);

CREATE TABLE Contacts
(
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	Email NVARCHAR(100),
	PhoneNumber NVARCHAR(20),
	PostAddress NVARCHAR(200),
	Website NVARCHAR(50)
);

CREATE TABLE Authors
(
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	ContactId INT NOT NULL FOREIGN KEY REFERENCES Contacts(Id)
);

CREATE TABLE Libraries
(
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	ContactId INT NOT NULL FOREIGN KEY REFERENCES Contacts(Id)
);

CREATE TABLE Books
(
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	Title NVARCHAR(100) NOT NULL,
	YearPublished INT NOT NULL,
	ISBN NVARCHAR(13) UNIQUE NOT NULL,
	AuthorId INT NOT NULL FOREIGN KEY REFERENCES Authors(Id),
	GenreId INT NOT NULL FOREIGN KEY REFERENCES Genres(Id)
);

CREATE TABLE LibrariesBooks
(
	LibraryId INT NOT NULL FOREIGN KEY REFERENCES Libraries(Id), 
	BookId INT NOT NULL FOREIGN KEY REFERENCES Books(Id),
	PRIMARY KEY (LibraryId, BookId)
);